# Generated by Django 5.0.6 on 2024-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_bookmodel_image_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
