# Generated by Django 5.0.6 on 2024-06-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['borrow_date']},
        ),
    ]
