# Generated by Django 5.0.6 on 2024-06-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_borrow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='Books.category'),
        ),
    ]
